# permissions for end users to edit clickhousekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clickhousekeeper-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clickhouse-operator
    app.kubernetes.io/part-of: clickhouse-operator
    app.kubernetes.io/managed-by: kustomize
  name: clickhousekeeper-editor-role
rules:
- apiGroups:
  - clickhouse.k8s.xjuzicloud.com
  resources:
  - clickhousekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clickhouse.k8s.xjuzicloud.com
  resources:
  - clickhousekeepers/status
  verbs:
  - get
